# Generated by Django 4.0 on 2022-11-23 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_comment_commenter_alter_post_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='commented_post',
        ),
    ]
