# Generated by Django 4.0 on 2022-11-23 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_post_comment_commented_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commented_post',
            new_name='post',
        ),
    ]
